# Generated by Django 4.1.5 on 2023-01-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='book',
            table='user',
        ),
    ]
