# Generated by Django 4.1.5 on 2023-01-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyshow', '0002_alter_book_phone_no_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
